# Generated by Django 3.1.5 on 2021-01-25 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('recipe', models.TextField()),
                ('kitchen', models.CharField(blank=True, max_length=300)),
                ('diet', models.CharField(blank=True, max_length=300)),
                ('calories', models.IntegerField(blank=True)),
                ('carbs', models.IntegerField(blank=True)),
                ('fats', models.IntegerField(blank=True)),
                ('proteins', models.IntegerField(blank=True)),
                ('timeOfCooking', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekMenus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='menu.dish')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
