# Generated by Django 3.1.5 on 2021-01-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('recipe', models.TextField()),
                ('kitchen', models.CharField(blank=True, max_length=300)),
                ('diet', models.CharField(blank=True, max_length=300)),
                ('calories', models.IntegerField(blank=True)),
                ('carbs', models.IntegerField(blank=True)),
                ('fats', models.IntegerField(blank=True)),
                ('proteins', models.IntegerField(blank=True)),
                ('timeOfCooking', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='menu.dish'),
            preserve_default=False,
        ),
    ]
